name: publish nuget

on:
  push:
    branches:
      - main

jobs:
  calc-version:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
      shortSha: ${{ steps.gitversion.outputs.shortSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.0.x'

      - name: Calculate version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          useConfigFile: true

  publish:
    needs: [calc-version]

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'src/Yh'

    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
          cache: true

      - name: Install dependencies
        run: dotnet restore $PROJECT

      - name: Build
        run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore

      - name: Package
        run: dotnet pack $PROJECT --configuration $BUILD_CONFIG --no-build --no-restore -p:Version=${{ needs.calc-version.outputs.semVer }}

      - name: Publish
        run: dotnet nuget push $PROJECT/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}